#ifndef PLAT_DETAILS_H
#define PLAT_DETAILS_H

#define SCREEN_W 240
#define SCREEN_H 160

// #define PLAT_HAS_MOUSE
// #define PLAT_HAS_TEXTENTRY
// #define PLAT_HAS_SCORESAVE

#define PLAT_FAKE_DUALSTICK

#endif // PLAT_DETAILS_H
